### ISSUE TITLE
Plugin not sending any data to Google

### ISSUE THREAD

**Issue by sts-ryan-holton** [MatteoGabriele/vue-gtag#262] opened 2021-01-21 13:50 UTC
I've got the latest version of Vue Gtag 1.10.0, and for some reason it's not sending any page view events or nothing to Google. Why is this?

```javaascript
import VueGtag from 'vue-gtag'

Vue.use(VueGtag, {
  config: {
    id: 'UA-91198233-2'
  }
})
```

My config remains unchanged, Vue 2 project

**Comment by TitanFighter** [comment] 2021-01-21 15:54
Do you see something like
```
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-91198233-2&amp;l=dataLayer" charset="utf-8"></script>
```
in the generated HTML?

**Comment by sts-ryan-holton** [comment] 2021-01-21 18:13
@TitanFighter I see that in the network request yes

**Comment by TitanFighter** [comment] 2021-01-21 19:01
do you see `page_view` event in `window.dataLayer`?

**Comment by ktmellow** [comment] 2021-01-22 04:59
I have the same issue. I have many page_view events in window.dataLayer array.

**Comment by sts-ryan-holton** [comment] 2021-01-22 06:51
@TitanFighter I see it yes, but no data is being sent to Google. It randomly stopped after about November last year

**Comment by pbujko** [comment] 2021-01-22 08:55
> @TitanFighter I see it yes, but no data is being sent to Google. It randomly stopped after about November last year

@sts-ryan-holton  - having exactly the same issue, no change on the client side and stopped reporting views over one night. Some time after we started seeing some impressions, views reported back - but we are certain it is not 100% of relevant data but rather only 50% of the traffic gets reported on google console.

**Comment by TomSinclair** [comment] 2021-01-22 10:46
Also having the same issue. The gtag script is generated and requested btu then data is sent. Turning on the debug mode is showing no data sent to GA.

**Comment by sts-ryan-holton** [comment] 2021-01-22 16:59
I just ended up pasting the original Google Analytics into my `*.vue` file as a temporary solution, of course, doesn't work for page navigation, but will work for whatever page is loaded on first page load. **Hopefully this core issue with this plugin can be fixed some time soon!!**

**Comment by MajorClod** [comment] 2021-01-29 00:48
I too am experiencing this.  Trying to use the out of the box setup.

Vue.use(VueGtag, {
  config: {
    id: "<MY_ID>", params: {
      send_page_view: false
    }
  }
}, router);

It looks like all of the page views are being sent to Google Analytics, but they're being logged under the overall Application Name, rather than the individual pages.

**Comment by MajorClod** [comment] 2021-01-29 07:04
> I too am experiencing this. Trying to use the out of the box setup.
> 
> Vue.use(VueGtag, {
> config: {
> id: "<MY_ID>", params: {
> send_page_view: false
> }
> }
> }, router);
> 
> It looks like all of the page views are being sent to Google Analytics, but they're being logged under the overall Application Name, rather than the individual pages.

Hmm I think I've fixed this for myself.  My problem is I didn't have name: defined in my routes, just path.

**Comment by mehmetgspace** [comment] 2021-02-27 19:02
If you add **send_page_view** param, it'll be work.

```
Vue.use(VueGtag, {
  config: {
    id: "UA-xxxxxxxxx-x",
    params: {
      send_page_view: true
    }
  }
});
```

**Comment by dennismetz** [comment] 2021-03-25 13:48
Same Problem, params send_page_view: true is not helping at all

**Comment by cloudnine-gjacob** [comment] 2021-03-25 15:04
I looked at the code and the send_page_view does not seem to be passed though and merged properly. As our customer was loosing her shit i just set it to true for now and the page views track properly.

allProperties.value.forEach(function (property) {
var params = Object.assign({
send_page_view: false
}, property.params);
query("config", property.id, params);
});

**Comment by MatteoGabriele** [comment] 2021-04-10 10:33
sorry to come back to you so late. @cloudnine-gjacob I am actually having no issue looking at my debugger:
the first config call for the initialization triggers a send_page_view = false, but all other page_view events have the send_page_view=true attached to them as you can see in the video here


https://user-images.githubusercontent.com/5337152/114266860-f79af980-99f8-11eb-97f9-c1998dbae0d4.mov

**Comment by MatteoGabriele** [comment] 2021-05-02 12:58
I will close this issue due to inactivities, but please feel free to re-open it once there is a reproduction of the issue available.

**Closed by MatteoGabriele** 2021-05-02 12:58 UTC
Labels: need more info, reproduction needed
